runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2

handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: /task.*
  script: main.app
  login: admin

- url: /admin.*
  script: main.app
  login: admin

- url: .*
  script: main.app

