application: project-open
version: 1
runtime: python
api_version: 1

handlers:
- url: /googlecf422d98732d787d.html
  static_files: static/googlecf422d98732d787d.html
  upload: static/googlecf422d98732d787d.html

- url: /static
  static_dir: static

- url: /task/.*
  script: main.py
  login: admin

- url: /wikisync.*
  script: main.py
  login: admin

- url: .*
  script: main.py
