application: project-open
version: 3
runtime: python
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: /task.*
  script: main.py
  login: admin

- url: /admin.*
  script: main.py
  login: admin

- url: .*
  script: main.py

builtins:
- datastore_admin: on
